words:
  - gomod
  - indepth
  - liblaf
  - liblaf's
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - makefile
  - npm
allowCompoundWords: true
