# https://github.com/lowlighter/metrics#-documentation

name: Metrics

on:
  schedule:
    - cron: 0 0 * * SUN
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_timezone: Asia/Shanghai

          base_indepth: yes

          plugin_achievements: yes

          plugin_activity: yes

          plugin_discussions: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes

          plugin_gists: yes

          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes

          plugin_introduction: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

          plugin_lines: yes
          plugin_lines_sections: base, repositories, history

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue

          plugin_people: yes
          plugin_people_shuffle: yes

          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_limit_discussions: 1000
          plugin_reactions_limit_discussions_comments: 1000
          plugin_reactions_details: count, percentage

          plugin_stargazers: yes
          plugin_stargazers_days: 0

          plugin_traffic: yes

      - run: |
          mkdir dist
          cp /metrics_renders/* dist/github-metrics.svg

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: assets
          single-commit: true
