name: README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  gen-readme:
    name: README
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-readme
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT || github.token }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install Prettier
        run: npm install --global prettier
      - name: Generate README
        run: ./scripts/gen-readme.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || github.token }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update `README.md`"
